# 결론

 첫 직장 월평균 임금은 공학계열이 가장 높았지만 이에 반해 만족도는 가장 낮게 나온 것으로 보아 복지가 안 좋을 것이라고 예상했다. 
교육계열이 다른 계열보다 임금이 낮은 편이지만 만족도는 가장 높은 걸로 보아 복지가 좋을 것이라고 생각했다. 

만족도는 교육계열, 의약계열, 인문계열, 사회계열, 예체능계열, 자연계열, 공학계열 순으로 높게 나타났다.

가장 높은 취업률을 보인 계열은 의약계열이고 가장 낮은 취업률을 보인 계열은 교육계열로 나타났다.

의약계열을 제외하고 모든 계열에서 남성의 취업률이 높은 것으로 나타났다. 
남녀의 성비가 가장 많이 차이났던 계열은 교육계열로 나타났다. 
남녀의 성비가 가장 적게 차이났던 계열은 사회계열로 나타났다. 
트리맵 라이브러리로도 남녀 성비에 따른 취업률 데이터를 시각화해봤으나 큰 차이가 나지 않아 bar플롯으로 결과를 나타냈다.

(취업률이 가장 높은 학과와 낮은 학과)
교육계열은 다른 계열들에 비해 취업률이 가장 낮게 나왔지만 유아특수재활학과는 가장 높은 취업률인 94%를 보였다.
공학계열에서는 재료과의 취업률이  88%로 가장 높았고 나노공학과의 취업률이 61%로 가장 낮았다. 
사회계열에서는 비서행정과의 취업률이 82%로 가장 높았고 사회교육학과가 35%로 가장 낮았다.
예체능 계열에서는 실용미술과의 취업률이 80%로 가장 높았고 관현악과가 42%로 가장 낮았다. 
의약계열에서는 치위생학과의 취업률이 91%로 가장 높았고 병원관리학과가 54%로 가장 낮았다.
인문계열에서는 인문학부의 취업률이 74%로 가장 높았고 일반사회교육과가 35%로 가장 낮았다. 
자연계열에서는 농수산과의 취업률이 77%로 가장 높았고 농생물학과가 53%로 가장 낮았다.

## Future Study

데이터 분석을 했지만 데이터가 첫 직장을 기준으로 하여 전체 직장인의 데이터보다 정확도가 떨어지는 점이 아쉬웠다.
데이터 제공기관의 실수로 2018년과 2019년 데이터를 비교해보지 못한 것이 아쉽다.
데이터 처리와 분석을 R스튜디오에서 하고 싶었지만 아직 부족하여 엑셀로 처리한 것이 약간 아쉽다.
데이터를 수집하는 데 있어서 조금 더 신중해야함을 느꼈다. 데이터를 시각화 하기 전에 꼭 데이터가 올바른 데이터인지
확인하는 과정이 필요하다고 느꼈다.
데이터를 수집하고 분석하는 부분의 R프로그래밍 실력을 길러 데이터 분석능력을 키우고 싶다.
