--- 
title: "학과별 취업 현황 분석 및 시각화"
author: "신은화, 최우진, 최유진"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "저희 프로젝트는 직업, 취업과 관련된 다양한 데이터들을 분석하고 처리하여 시각화하는 것입니다. 조원들이 곧 고학년이 되기에 시각화 자료가 필요한 부분도 있지만, 청소년 때의 경험이 이 프로젝트를 구상하는 데에 큰 영향을 끼쳤습니다. 청소년 때 진로와 전공 선택을 하는 부분에 있어서 시각화 된 자료들도 별로 없고 정리가 되어있지 않아서 자료를 찾는 데에 어려움을 겪었습니다. 때문에, 전국의 모든 대학교, 모든 학과의 직업, 취업 관련 데이터를 종합해 시각화 자료를 만들어 도움을 주고 싶었습니다. 직업 만족도, 취업률, 임금 총 세 가지의 데이터를 사용하여 좋은 시각화 자료를 만들어 대학생, 청소년들이 진로를 정할 때 조금이라도 도움이 되고자 해당 프로젝트를 기획하게 되었습니다."
---
# 수업과 팀원 소개 {-}


__*This book is a final report of a capstone project by [Team Name].*__

__Team Members__: 신은화, 최우진, 최유진

__Course Name__: Foundations of Data Science with Capstone at SMU

__Course Term__: Summer 2021

__Course Description__: Data science is the interdisciplinary study of the tools and theory behind using data to extract knowledge. It combines ideas from statistics, computer science, and particular domains in the physical and social sciences in order to make predictions and optimal decisions.

This SMU summer intensive course is designed with a practical approach. The students will be guided to learn the basics and move on to more advanced topics in 2 weeks. The final 1 week will be dedicated to practicing and presenting data science skills and competency through capstone projects. 

The Data Science Capstone is a team-based, project-based session, providing an opportunity to apply data science skills and knowledge obtained from the first 2 weeks of the foundation session. Teams of two or three students, under the direction of the course instructor and teaching assistants, will be working on a data project. The primary objective is to educate the students in solving real world data science problems in professional settings by leveraging their own computational, statistical, and domain skills. 

The capstone requires two outcomes: A final report (this book) and a final presentation.



